-- Optional but recommended
create extension if not exists "pgcrypto";

-- =========================================================
-- 1) PROFILES
-- =========================================================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  full_name text,
  avatar_url text,
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================================================
-- 2) ENTRIES
-- One row = one user tracking one TMDB title
-- =========================================================
create table if not exists public.entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,

  tmdb_id integer not null,
  media_type text not null check (media_type in ('movie', 'tv')),

  status text not null default 'plan_to_watch'
    check (status in ('plan_to_watch', 'watching', 'completed', 'dropped', 'on_hold')),

  episodes_watched integer not null default 0 check (episodes_watched >= 0),
  rating integer check (rating between 1 and 10),
  note text,

  started_at timestamptz,
  finished_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (user_id, tmdb_id, media_type)
);

-- =========================================================
-- 3) LISTS
-- Custom user lists
-- =========================================================
create table if not exists public.lists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,

  title text not null,
  description text,

  is_public boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (user_id, title)
);

-- =========================================================
-- 4) LIST_ENTRIES
-- Join table between lists and TMDB items
-- =========================================================
create table if not exists public.list_entries (
  id bigint generated by default as identity primary key,
  list_id bigint not null references public.lists(id) on delete cascade,

  tmdb_id integer not null,
  media_type text not null check (media_type in ('movie', 'tv')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (list_id, tmdb_id, media_type)
);

-- =========================================================
-- INDEXES
-- =========================================================
create index if not exists entries_user_id_idx on public.entries(user_id);
create index if not exists entries_tmdb_idx on public.entries(tmdb_id, media_type);
create index if not exists lists_user_id_idx on public.lists(user_id);
create index if not exists list_entries_list_id_idx on public.list_entries(list_id);

-- =========================================================
-- updated_at helper
-- =========================================================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists set_entries_updated_at on public.entries;
create trigger set_entries_updated_at
before update on public.entries
for each row execute procedure public.set_updated_at();

drop trigger if exists set_lists_updated_at on public.lists;
create trigger set_lists_updated_at
before update on public.lists
for each row execute procedure public.set_updated_at();

drop trigger if exists set_list_entries_updated_at on public.list_entries;
create trigger set_list_entries_updated_at
before update on public.list_entries
for each row execute procedure public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data ->> 'username',
      split_part(new.email, '@', 1)
    )
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.entries enable row level security;
alter table public.lists enable row level security;
alter table public.list_entries enable row level security;


create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using ((select auth.uid()) = id);

create policy "profiles_insert_own"
on public.profiles
for insert
to authenticated
with check ((select auth.uid()) = id);

create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);



create policy "entries_select_own"
on public.entries
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "entries_insert_own"
on public.entries
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "entries_update_own"
on public.entries
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "entries_delete_own"
on public.entries
for delete
to authenticated
using ((select auth.uid()) = user_id);


create policy "lists_select_own_or_public"
on public.lists
for select
to authenticated
using (
  ((select auth.uid()) = user_id) or (is_public = true)
);

create policy "lists_insert_own"
on public.lists
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "lists_update_own"
on public.lists
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "lists_delete_own"
on public.lists
for delete
to authenticated
using ((select auth.uid()) = user_id);



create policy "list_entries_select_if_owner_or_public_list"
on public.list_entries
for select
to authenticated
using (
  exists (
    select 1
    from public.lists l
    where l.id = list_entries.list_id
      and (
        l.user_id = (select auth.uid())
        or l.is_public = true
      )
  )
);

create policy "list_entries_insert_if_list_owner"
on public.list_entries
for insert
to authenticated
with check (
  exists (
    select 1
    from public.lists l
    where l.id = list_entries.list_id
      and l.user_id = (select auth.uid())
  )
);

create policy "list_entries_update_if_list_owner"
on public.list_entries
for update
to authenticated
using (
  exists (
    select 1
    from public.lists l
    where l.id = list_entries.list_id
      and l.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.lists l
    where l.id = list_entries.list_id
      and l.user_id = (select auth.uid())
  )
);

create policy "list_entries_delete_if_list_owner"
on public.list_entries
for delete
to authenticated
using (
  exists (
    select 1
    from public.lists l
    where l.id = list_entries.list_id
      and l.user_id = (select auth.uid())
  )
);


alter table public.entries
add column if not exists title text;
alter table public.entries
add column if not exists poster_path text;


drop table if exists public.follows;

create table public.follows (
    id serial primary key,
    follower_id uuid not null references public.profiles(id) on delete cascade,
    following_id uuid not null references public.profiles(id) on delete cascade,
    created_at timestamp default current_timestamp,
    unique (follower_id, following_id)
);


create or replace function public.get_user_id_by_email(p_email text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid;
begin
  select id into uid
  from auth.users
  where email = p_email;

  return uid;
end;
$$;

grant execute on function public.get_user_id_by_email(text) to authenticated;


create or replace function public.get_my_friends()
returns table (
  id uuid,
  username text,
  bio text,
  avatar_url text
)
language sql
security definer
as $$
  select
    p.id,
    p.username,
    p.bio,
    p.avatar_url
  from public.follows f
  join public.profiles p
    on p.id = f.following_id
  where f.follower_id = auth.uid();
$$;

grant execute on function public.get_my_friends() to authenticated;


create or replace function public.get_my_following()
    returns table (
                      id uuid,
                      username text,
                      bio text,
                      avatar_url text
                  )
    language sql
    security definer
as $$
select
    p.id,
    p.username,
    p.bio,
    p.avatar_url
from public.follows f
         join public.profiles p
              on p.id = f.following_id
where f.follower_id = auth.uid();
$$;

grant execute on function public.get_my_following()
    to authenticated;


create or replace function public.get_my_followers()
    returns table (
                      id uuid,
                      username text,
                      bio text,
                      avatar_url text
                  )
    language sql
    security definer
as $$
select
    p.id,
    p.username,
    p.bio,
    p.avatar_url
from public.follows f
         join public.profiles p
              on p.id = f.follower_id
where f.following_id = auth.uid();
$$;

grant execute on function public.get_my_followers()
    to authenticated;


create policy "Allow read for all users"
on profiles
for select
using (true);


create policy "Allow read for all entries"
on entries
for select
using (true);
